### ISSUE TITLE
При формировании отчёта накладных и ЭСЧФ за месяц май/июнь "дата ТТН" выбирается за апрель

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#12]
(ЭСЧФ - Входящие ЭСЧФ - Печать - Накладные->ЭСЧФ)
![ттн эсчф](https://user-images.githubusercontent.com/88382934/129182396-9975294d-0698-42bc-a9f5-cbc6dcffb631.jpg)
![ттн эсчф2](https://user-images.githubusercontent.com/88382934/129182716-de9da5ce-d179-49a1-ac92-18a3bb15e65c.jpg)

**Comment by aer1k** [comment]
Исправил. Переподключитесь к "Гедымину" и проверьте. Если всё хорошо -- закрывайте вопрос.

**Comment by adminvolmk** [comment]
да, всё работает, спасибо большое
 
 
С уважением,
Бабаш Антон Игоревич
Инженер-программист
ОАО "Волковысский мясокомбинат"
моб. тел.   +37529-7540687

**Comment by aer1k** [comment]
> да, всё работает, спасибо большое

Отлично. Пожалуйста.
