### ISSUE TITLE
Ошибка при списывании материалов

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#13]
![12](https://user-images.githubusercontent.com/88382934/129199038-3d075924-b94d-4f9d-b419-8aedf59106fb.jpg)

**Comment by gs7600300** [comment]
Не вижу тут ошибки. Да, когда 2 пользователя открывают один документ возникает конфликт транзакций о чем сообщает данное окно. Попробовал на разных документах этого типа проблем не заметил. Пока закрываю. Если можете описать как это повторить не открывая один документ два раза - откроем и будем смотреть.
