### ISSUE TITLE
Новая карточка. Выдает ошибку как только ставим галочку "весовой товар"

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#16]
![14 jpg](https://user-images.githubusercontent.com/88382934/129885528-5efb14ec-e14b-455b-8ef8-cbc70d60644f.png)

**Comment by yoannawx** [comment]
какой-то пользователь вбил руками в код весового товара 0,2. найдите эту карточку и очистите поле с кодом

**Comment by adminvolmk** [comment]
Проблема устранена, спасибо.
А возможно ли сделать контроль, чтобы в «код весового товара» вводились только целые трёхзначные числа?

**Comment by gs7600300** [comment]
В поле код весового товара вообще ничего вводить не нужно, он должен генерироваться сам.
