### ISSUE TITLE
Акт сверки по клиенту. Бухгалтера спрашивают, возможно ли сделать в "параметрах"(фото 1) выбор(галочку) для Руководителя и главного бухгалтера. Иногда в актах их подпись не нужна

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#19]
![акт2](https://user-images.githubusercontent.com/88382934/130934303-527c72fe-d9ac-474e-8a59-aab68d338f19.png)
![акт1](https://user-images.githubusercontent.com/88382934/130934327-04a8623d-3d97-46b2-b650-8c32c4648da2.png)

**Comment by gs7600300** [comment]
Эталонный отчет лучше не изменять. Возможно сделать копию и в ней это предусмотреть.
