### ISSUE TITLE
Почему наличные по журналу ордеру по счету 50.1 не совпадают в кассовом отчете, тоже самое и по безналу... Магазин Николаева, руками ничего не заносят

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#21]

**Comment by gs7600300** [comment]
Проводка по 50.1 счету формируется по кассовой книге. 
Кассовая книга формируется на основании приходных и расходных кассовых ордеров, которые **вносятся пользователем**. Если есть вопросы в ЖО по 50.1 по конкретному магазину, за конкретную дату - идем в кассовую книгу по этому магазину и смотрим.. 

Кассовый отчет загружается автоматически на магазинах с количественным учетом и вносится вручную по суммовым. 
Кассовый отчет должен совпадать с Z-отчетом.
