### ISSUE TITLE
В магазине в г.Гродно хотят сделать "Возврат товара поставщику"(картинка 1) - ФИЛИАЛ №1 НЕСТ ИООО "АЛИДИ-ВЕСТ". Но приход был был из остатков и поставщик в накладной прописан "мясокомбинат"(картинка 2). Как правильно сделать возврат в таком случае?

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#23]
![1](https://user-images.githubusercontent.com/88382934/133569593-95863dd9-b6b7-485a-8faf-0deb99984242.png)
![2](https://user-images.githubusercontent.com/88382934/133569605-f8d03b5e-76a8-4b0e-8aa0-7b4e7ee8b600.png)

**Comment by gs7600300** [comment]
Задача не стандартная. Для решения её, нужно:
1) Отключить часть метода таблицы в которой выполняется подстановка поставщика из шапки документа в позицию;
2) В поле Поставщик позиции подставить верного поставщика;
3) Откомментировать часть метода назад;

Для того, чтобы закомментировать нужную часть метода:
1) Нажимаем на позицию документа правой кнопкой мыши, выбираем пункт "Свойства";
2) В появившемся диалоговом окне нажимаем "Методы класса";
3) В окне "Редактор скрипт объектов" , находим метод DOBEFOREPOST для TgdcInvDocumentLine147010993_109092844 и выбираем для редактирования;
4) По тексту находим вызов функции OptInv_AddwBillLine_DoBeforePost, выделяем её и нажимаем ctrl+Enter для перехода на неё;
5) В функции комментируем часть кода, как показано ниже:
```
'    if Assigned(Self.OwnerForm) then
'      If Self.OwnerForm.VariableExists("NotFillProvider") then
'        If Not Self.OwnerForm.Variables("NotFillProvider") Then
'          Self.FieldByName("to_usr$inv_provider").AsInteger = Self.MasterSource.DataSet.FieldByName("usr$contactkey").AsInteger
'        End If
'      else
'        Self.FieldByName("to_usr$inv_provider").AsInteger = Self.MasterSource.DataSet.FieldByName("usr$contactkey").AsInteger
'      end if
'    Else
'      Self.FieldByName("to_usr$inv_provider").AsInteger = Self.MasterSource.DataSet.FieldByName("usr$contactkey").AsInteger
'    End If
```

**Comment by MAliaksandr** [comment]
Может быть проще сделать документ переоценки и изменить поставщика для определенного количества товара? Если, конечно, там есть признаки "поставщик"
