### ISSUE TITLE
Когда открыта вкладка "Ошибки при импорте КС" идёт нагрузка на ЦП терминального сервера, когда вкладку закрываешь - нагрузка пропадает

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#4]
![01](https://user-images.githubusercontent.com/88382934/128326513-9560194f-558c-4e21-a7c1-60c651b8c2f9.jpg)
![02](https://user-images.githubusercontent.com/88382934/128326547-caec617e-fa8d-482d-b183-9eaefc406db1.jpg)
![03](https://user-images.githubusercontent.com/88382934/128326576-57beaaba-1759-473c-940f-f85b7605fe51.jpg)

**Comment by gs7600300** [comment]
Исправлено.
