### ISSUE TITLE
При пересчете цен к цене сока не добавляется цена стеклобанки

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#5]
![04](https://user-images.githubusercontent.com/88382934/128327601-a6f14cc9-a04f-4d94-9711-c9957978bd84.jpg)

**Comment by adminvolmk** [comment]
выбрали другую банку и всё пересчиталось.
существует ли какой-то признак в карточке стеклобанки, который влияет на перерасчёт розничной цены?

**Comment by gs7600300** [comment]
В руководстве подробно описаны все особенности оприходования товара в упаковке (стеклопосуда).  Конкретно в Вашем случае не верно заполнен справочник единиц измерения.
