### ISSUE TITLE
Переоценка товара

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#6]
Сумма переоценки товара по документу 519 от 02.07 равна -0,17 копеек. по счетам сумма составляет 1,03.
![05](https://user-images.githubusercontent.com/88382934/128328820-adccd60a-6d4b-4a01-bb46-22fb3a85a693.jpg)
![06](https://user-images.githubusercontent.com/88382934/128328834-c5892388-0f17-483a-bf21-0ffa2d08c811.jpg)
![07](https://user-images.githubusercontent.com/88382934/128328847-8c372b26-3c2c-40f5-a6fe-1d45f6219e9d.jpg)

**Comment by gs7600300** [comment]
Проверено. Отражено все верно.
