### ISSUE TITLE
ошибки при формировании кассового отчёта

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#7]
![08](https://user-images.githubusercontent.com/88382934/128460506-60e852a9-89f4-4f3b-8343-b3a442850441.jpg)
![09](https://user-images.githubusercontent.com/88382934/128460520-73fb4581-5637-4f6c-805d-3e0e9e7cb629.jpg)

**Comment by gs7600300** [comment]
Сообщение deadlock значит, что транзакция заблокирована. Именно сейчас другой пользователь изменяет документ, который попадает в выборку отчета.
