### ISSUE TITLE
При продаже на кассах товар выбивается в двух строчках

### ISSUE THREAD

**Issue by adminvolmk** [gs7600300/FT_VolMk#9]
![10](https://user-images.githubusercontent.com/88382934/128706525-da291f3f-f6e9-42dd-84e9-f20a37a75ed2.jpg)
![11](https://user-images.githubusercontent.com/88382934/128706546-5392bcc7-f481-4910-a449-da97f11694d8.jpg)

**Comment by gs7600300** [comment]
Случай со сметаной БРЕСТ-ЛИТОВСКАЯ разбирали, там было слияние товаров. В справочнике Уникальные ШК, два ШК в признаках различные ID товара. Один верный второго уже нет на базе.

**Comment by yasorokin** [comment]
А можно ли пройтись по БД КС и удалить (сделать неактивным для касс) из прайса товар, которого нет в Справочнике ТМЦ?
